name: 'QR Code Commenter'
on: 
  pull_request:
    types: [edited]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - name: print URL
        id: print-url
        run: |
          echo ::set-output name=url::https://blog.kentarom.com/
      - uses: kentaro-m/qr-code-commenter-action@60c0c17
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          content: "${{steps.print-url.outputs.url}}"
          comment: |
            :lock: This is a QR code for access to the preview website.
            :iphone: Scan a code with your device.
            {qrcode}
