name: 'QR Code Commenter'
on: 
  pull_request:
    types: [edited]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/qr-code-commenter-action@60c0c17
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          content: https://blog.kentarom.com/
          comment: |
            Hi, Ken! This is test {qrcode} for QR Code Commenter.
            {qrcode}
